---
- name: Create virtual host configuration file from template
  template:
    src: virtual_host_ssl.conf.j2
    dest: /etc/nginx/conf.d/{{ item }}.conf
    mode: '0644'
  loop: "{{ nginx_virtual_hosts|flatten(levels=1) }}"
  notify: nginx_reload