---
- name: Install nginx package
  apt:
    name:
      - nginx={{ nginx_version }}
    state: present
  notify: nginx_enable

- name: Create nginx.conf from template
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: '0644'
  notify: nginx_reload